version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  adhoc:
    macos:
      xcode: "11.4.1"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: beta
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
workflows:
    adhoc:
      jobs:
        - build-and-test
        - adhoc