version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    macos:
      xcode: "11.4.1"
    executor:
      name: node/default
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: bundle install
      - run:
        name: Fastlane
        command: bundle exec fastlane $FASTLANE_LANE
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - store_artifacts:
        path: output
      - store_test_results:
        path: output/scan

  adhoc:
    macos:
      xcode: "11.4.1"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: beta
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
workflows:
    build-and-test:
      jobs:
        - build-and-test
        - adhoc