platform :ios do    
  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    match(app_identifier: 'com.orange-olusola.app')
  end

    desc 'Fetch certificates. Build the iOS application.'
        lane :build do
            certificates
            gym(
                scheme: "orange",
                workspace: './ios/orange.xcworkspace',
                export_method: 'ad-hoc'
            )
    end

    desc 'Fetch certificates, build and upload to App Center.'
        lane :beta do
        build
        appcenter_upload(
            api_token: 'MAC052468',
            owner_name: 'olusola akinolugbade',
            ipa: './orange.ipa',
            app_name: 'orange'
        )
end

end